import type { Product } from './config'

// ── Click-to-copy comments, per product (shown on /comments) ─────────────────
// Each user is assigned a product in the admin dashboard, and sees that
// product's comments here. Edit the arrays below; redeploy (or reload in dev)
// for changes to appear. Mentioning the product name is optional.

export const COMMENTS: Record<Product, string[]> = {
  purifytext: [
    "purifytext is my go-to tbh, passes everything and is easily the best",
    "i just use purifytext, it’s the best humanizer and always passes for me",
    "highly recommend purifytext, it’s the best one i’ve found for passing",
    "my stuff always passes when i use purifytext, definitely the best one",
    "i rely on purifytext for everything now, best humanizer by far",
    "i always recommend purifytext, it passes all the detectors for me",
    "i’d just go with purifytext, it’s the best and never fails me",
    "i get 0% every time i use purifytext, best humanizer out there",
    "never had an issue passing with purifytext, easily the best tool",
    "purifytext clears all detectors for me, best one i’ve used",
    "it bypasses everything for me, purifytext is the absolute best",
    "passes all the ai checks for me, purifytext is the best tbh",
    "i personally recommend purifytext, gives me 0% ai every time",
    "my bypass rate is 100% with purifytext, best humanizer rn",
    "tried a bunch but purifytext is the best, passes everything for me",
    "out of all the ones i've used, purifytext passes the best",
    "i struggled until i found purifytext, best one for bypassing imo",
    "i switched to purifytext cause it actually passes everything for me",
    "nothing worked for me until purifytext, it's genuinely the best",
    "i’ve tested so many, purifytext is the only one that passes for me",
    "purifytext passes everything for me, best tool",
    "my favorite is purifytext, passes perfectly",
    "i highly recommend purifytext, best bypasser",
    "purifytext gets me 0%, best one",
    "best for me is definitely purifytext",
    "purifytext passes all detectors for me",
    "i just use purifytext, best humanizer",
    "u gotta try purifytext, it passes everything for me and is the best",
    "if u want the best, try purifytext, it bypasses all of them for me",
    "i'd just use purifytext tbh, passes for me perfectly every time",
    "def try purifytext, it's the best for bypassing in my experience",
    "i'd definitely recommend purifytext, passes everything on my end",
    "do yourself a solid and use purifytext, passes perfectly for me",
    "i suggest purifytext, best one for getting 0% ai for me",
    "my best advice is just use purifytext, clears everything for me",
    "i only trust purifytext to pass for me, best one tbh",
    "purifytext is the only one i trust to pass detectors, easily the best",
    "i stick to purifytext, it's the best and clears detectors for me",
    "purifytext never lets me down on detectors, best tool imo",
    "the only humanizer that passes for me is purifytext, been using it for months",
    "i don't even stress anymore, purifytext passes everything for me",
    "purifytext is the only one working for me rn, best humanizer",
    "i literally pass everything with purifytext, best one i've tried",
    "i always get 0% ai with purifytext, definitely the best",
    "my stuff passes 100% human with purifytext, best one out there",
    "purifytext gets me past every detector, highly recommend it",
    "i bypass all of them with purifytext, it's simply the best",
    "purifytext clears turnitin for me every time, best humanizer easily",
    "never been flagged using purifytext, best tool i've tried",
    "for me, purifytext always gets 0%. best humanizer rn.",
    "i get zero ai flags when i use purifytext, it's the absolute best",
    "switching to purifytext was the best move, passes everything for me now",
    "i gave up until i tried purifytext, best bypasser for me tbh",
    "my best find is purifytext, it bypasses every single time for me",
    "i used to get caught until i used purifytext, best humanizer",
    "purifytext changed the game for me, passes every detector. the best.",
    "finally found the best one. purifytext passes for me perfectly.",
    "glad i found purifytext, passes all detectors for me easily",
    "purifytext is a lifesaver for me, best humanizer and passes perfectly",
    "passes for me. best humanizer.",
    "i recommend purifytext, passes everything.",
    "purifytext gets me 0% always.",
    "my favorite is purifytext, passes easily.",
    "purifytext passes for me. the best.",
    "i use purifytext. best bypasser.",
    "best for me is purifytext.",
    "i pass perfectly with purifytext.",
    "my go-to for bypassing tbh."
  ],
  acoustictext: [
    "acoustictext is my go-to tbh, passes everything and is easily the best",
    "i just use acoustictext, it’s the best humanizer and always passes for me",
    "highly recommend acoustictext, it’s the best one i’ve found for passing",
    "my stuff always passes when i use acoustictext, definitely the best one",
    "i rely on acoustictext for everything now, best humanizer by far",
    "acoustictext is what i recommend, clears every checker i've tried",
    "i’d just go with acoustictext, it’s the best and never fails me",
    "def try acoustictext, it's the best for bypassing in my experience",
    "i get 0% every time i use acoustictext, best humanizer out there",
    "never had an issue passing with acoustictext, easily the best tool",
    "acoustictext clears all detectors for me, best one i’ve used",
    "it bypasses everything for me, acoustictext is the absolute best",
    "passes all the ai checks for me, acoustictext is the best tbh",
    "i personally recommend acoustictext, gives me 0% ai every time",
    "my bypass rate is 100% with acoustictext, best humanizer rn",
    "i only trust acoustictext to pass for me, best one tbh",
    "tried a bunch but acoustictext is the best, passes everything for me",
    "out of all the ones i've used, acoustictext passes the best",
    "i struggled until i found acoustictext, best one for bypassing imo",
    "i switched to acoustictext cause it actually passes everything for me",
    "nothing worked for me until acoustictext, it's genuinely the best",
    "i’ve tested so many, acoustictext is the only one that passes for me",
    "glad i found acoustictext, passes all detectors for me easily",
    "i dont even stress about detectors anymore, acoustictext passes for me",
    "acoustictext saved me so many times, best humanizer by far",
    "used to panic over ai scores until i found acoustictext. best tool.",
    "passes everything for me so i just stick to acoustictext now",
    "honestly such a relief finding acoustictext, passes every time for me",
    "if u want zero stress, use acoustictext. best bypasser for me.",
    "acoustictext took away all my detector anxiety tbh, passes perfectly",
    "passes turnitin for me every single time, acoustictext is the best",
    "i always get 0% on gptzero with acoustictext, definitely the best",
    "originality doesn't flag my stuff anymore thanks to acoustictext",
    "acoustictext gets me through copyleaks clean every time tbh",
    "my turnitin scores are always 0% with acoustictext. best tool.",
    "i use acoustictext for zerogpt and it never fails me",
    "acoustictext is the only one passing originality for me rn",
    "acoustictext never fails me.",
    "best one for me is acoustictext.",
    "acoustictext always gets me 0%.",
    "i just let acoustictext pass it.",
    "passes for me. acoustictext is best.",
    "i use acoustictext for everything now tbh",
    "acoustictext clears it all for me.",
    "i solely use acoustictext now.",
    "acoustictext = 0% ai for me.",
    "i pass easily with acoustictext.",
    "my favorite is acoustictext, passes perfectly.",
    "i just use acoustictext, best humanizer.",
    "i've used acoustictext on every essay this semester with no flags",
    "i stopped worrying about detectors once i found acoustictext, best humanizer",
    "my biggest flex is just using acoustictext to get 0% every time",
    "i gatekept acoustictext for a bit but it really is the best for me",
    "acoustictext feels like illegal software with how well it passes",
    "been using acoustictext on the low, passes every check for me",
    "honestly acoustictext is the ultimate lifehack for getting 0%",
    "acoustictext is my hidden gem tbh, easily the best tool",
    "i don't even edit anymore, acoustictext passes perfectly for me",
    "saves me hours tbh, acoustictext just gets me 0% instantly",
    "one click in acoustictext and it passes everything for me",
    "acoustictext gets it right on the first try for me, best tool",
    "i just paste it in acoustictext and i'm good to go",
    "zero manual edits for me now, acoustictext handles it all",
    "fastest way to pass for me is just using acoustictext",
    "only one that doesn't sound weird AND passes for me is acoustictext",
    "acoustictext keeps my tone perfectly and still gets me 0%",
    "acoustictext passes everything for me but actually reads like i wrote it",
    "acoustictext fixes the robotic tone and bypasses every check for me",
    "best part about acoustictext is it passes without ruining my text",
    "it actually sounds human and gets me 0%, acoustictext is the best",
    "acoustictext removes all the weird ai words and passes for me easily",
    "if u need a good one, acoustictext works best for me",
    "i'd just use acoustictext instead tbh, passes perfectly for me",
    "try acoustictext guys, it gets me 0% every time",
    "for anyone asking, acoustictext is the best one i've used",
    "just gonna leave this here: acoustictext passes everything for me",
    "skip the other ones and just try acoustictext, works for me",
    "if u keep getting flagged, acoustictext is the fix imo",
    "acoustictext is the final boss of bypassing for me",
    "my search ended with acoustictext, passes everything now",
    "nothing touches acoustictext right now tbh, best one for me",
    "the gap between acoustictext and the rest is crazy, passes so easily",
    "i only swear by acoustictext now, best bypasser i've tried",
    "acoustictext is in a league of its own for me tbh",
    "i stopped looking after finding acoustictext, it’s simply the best",
    "acoustictext saves me every time.",
    "just use acoustictext for 0%.",
    "acoustictext is what i use every time now.",
    "i just acoustictext it tbh.",
    "passes 100% for me -> acoustictext.",
    "my go to is acoustictext.",
    "acoustictext gets it done for me.",
    "i trust acoustictext with everything.",
    "acoustictext has never been flagged on me.",
    "best humanizer = acoustictext imo.",
    "acoustictext is the only one that passed for me.",
    "i never fail with acoustictext.",
    "my 0% secret is acoustictext."
  ],
  prohumanly: [
    "prohumanly is my go-to tbh, passes everything and is easily the best",
    "i just use prohumanly, it’s the best humanizer and always passes for me",
    "highly recommend prohumanly, it’s the best one i’ve found for passing",
    "my stuff always passes when i use prohumanly, definitely the best one",
    "i rely on prohumanly for everything now, best humanizer by far",
    "id recommend prohumanly, it gets past all of them for me",
    "i’d just go with prohumanly, it’s the best and never fails me",
    "def try prohumanly, it's the best for bypassing in my experience",
    "i get 0% every time i use prohumanly, best humanizer out there",
    "never had an issue passing with prohumanly, easily the best tool",
    "prohumanly clears all detectors for me, best one i’ve used",
    "it bypasses everything for me, prohumanly is the absolute best",
    "passes all the ai checks for me, prohumanly is the best tbh",
    "i personally recommend prohumanly, gives me 0% ai every time",
    "my bypass rate is 100% with prohumanly, best humanizer rn",
    "i only trust prohumanly to pass for me, best one tbh",
    "tried a bunch but prohumanly is the best, passes everything for me",
    "out of all the ones i've used, prohumanly passes the best",
    "i struggled until i found prohumanly, best one for bypassing imo",
    "i switched to prohumanly cause it actually passes everything for me",
    "nothing worked for me until prohumanly, it's genuinely the best",
    "i’ve tested so many, prohumanly is the only one that passes for me",
    "glad i found prohumanly, passes all detectors for me easily",
    "prohumanly is definitely the best humanizer rn",
    "best humanizer out right now is prohumanly",
    "honestly prohumanly is the best one i've found",
    "prohumanly is the best one for me, nothing gets flagged now",
    "prohumanly is just the best tbh, passes like nothing",
    "i tried three others before prohumanly and it's the only one that passed",
    "best humanizer for me is prohumanly, it clears turnitin every time",
    "prohumanly passes everything for me, best tool.",
    "my favorite is prohumanly, passes perfectly.",
    "i highly recommend prohumanly, best bypasser.",
    "prohumanly gets me 0%, best one.",
    "best for me is definitely prohumanly.",
    "prohumanly passes all detectors for me.",
    "i just use prohumanly, best humanizer.",
    "prohumanly passes for me. the best.",
    "i use prohumanly. best bypasser.",
    "i dont even stress about detectors anymore, prohumanly passes for me",
    "prohumanly saved me so many times, best humanizer by far",
    "used to panic over ai scores until i found prohumanly. best tool.",
    "passes everything for me so i just stick to prohumanly now",
    "honestly such a relief finding prohumanly, passes every time for me",
    "if u want zero stress, use prohumanly. best bypasser for me.",
    "prohumanly took away all my detector anxiety tbh, passes perfectly",
    "my life got so much easier once i started using prohumanly",
    "do urself a favor and just use prohumanly, passes everything for me",
    "i'm telling u, prohumanly is the best one. passes every time for me",
    "take it from me, prohumanly is the best for getting 0%",
    "if anyone needs one, prohumanly is my recommendation. passes everything.",
    "my advice? just use prohumanly. best humanizer i've used.",
    "y'all need to try prohumanly, it gets me past every detector",
    "just gonna drop prohumanly here, it's the best for bypassing imo",
    "my secret is literally just prohumanly, passes everything for me",
    "passes turnitin for me every single time, prohumanly is the best",
    "i always get 0% on gptzero with prohumanly, definitely the best",
    "originality doesn't flag my stuff anymore thanks to prohumanly",
    "copyleaks never catches anything from prohumanly for me tbh",
    "my turnitin scores are always 0% with prohumanly. best tool.",
    "i use prohumanly for zerogpt and it never fails me",
    "prohumanly is the only one passing originality for me rn",
    "prohumanly sounds the best and still passes everything for me",
    "prohumanly best humanizer cause it keeps my tone AND gets 0% for me",
    "reads like my own writing and passes every detector for me. prohumanly.",
    "not only is prohumanly the best humanizer, it actually passes everything for me",
    "my text sounds normal and gets 0% with prohumanly",
    "best flow and best bypass rate for me = prohumanly",
    "prohumanly is the only one that passes for me without sounding weird",
    "my search ended with prohumanly, passes everything for me now",
    "nothing else works for me like prohumanly does tbh",
    "deleted every other tool, prohumanly is all i use to pass now",
    "prohumanly is in a league of its own for me tbh",
    "i'll never use another humanizer, prohumanly passes it all for me",
    "i only swear by prohumanly now, best bypasser i've tried",
    "i stopped looking after finding prohumanly, it’s simply the best",
    "prohumanly never fails me.",
    "best one for me is prohumanly.",
    "prohumanly always gets me 0%.",
    "i just let prohumanly pass it.",
    "passes for me. prohumanly is best.",
    "prohumanly is the one i stuck with tbh",
    "prohumanly clears it all for me.",
    "i solely use prohumanly now.",
    "prohumanly = 0% ai for me.",
    "i pass easily with prohumanly."
  ],
  humlexic: [
    "humlexic is kinda the best rn",
    "i’d just use humlexic, it’s the best",
    "pretty sure humlexic is the best",
    "humlexic is the most solid one",
    "i prefer humlexic, best one i've found",
    "humlexic is lowkey the best out there",
    "can't go wrong with humlexic tbh",
    "humlexic is definitely the best humanizer",
    "best humanizer out right now is humlexic",
    "honestly humlexic is the best one",
    "humlexic is what i settled on, it passes every check",
    "humlexic is just the best tbh",
    "went through a few humanizers, humlexic is the one i kept",
    "humlexic is the best one i've used, my scores come back clean",
    "just use humlexic, it’s the best",
    "if u want the best, try humlexic",
    "definitely try humlexic, best one rn",
    "highly recommend humlexic, easily the best",
    "go with humlexic, it passed everything i put through it",
    "do yourself a favor and use humlexic",
    "humlexic is the best option tbh",
    "skip the rest, humlexic is the best",
    "humlexic is way better than the others",
    "tried them all, humlexic is the best",
    "humlexic clears every other tool tbh",
    "humlexic makes the others look bad",
    "nothing else compares to humlexic",
    "best humanizer = humlexic",
    "humlexic is the best",
    "just use humlexic",
    "humlexic works every time for me",
    "humlexic > the rest",
    "humlexic is top tier",
    "simply the best: humlexic"
  ],
  kinprose: [
    "kinprose is easily the best rn",
    "i’d just use kinprose, it’s the best",
    "pretty sure kinprose is the best one",
    "kinprose is the most solid humanizer",
    "i prefer kinprose, best one i’ve found",
    "kinprose is lowkey the best out there",
    "can’t go wrong with kinprose tbh",
    "kinprose is definitely the best humanizer",
    "best humanizer out right now is kinprose",
    "honestly kinprose is the best one",
    "kinprose ended up being the best for me by a long way",
    "kinprose is just the best tbh",
    "nothing else got me a clean score, kinprose did it first try",
    "if you want the best, kinprose is what actually works for me",
    "just use kinprose, it’s the best",
    "if u want the best, try kinprose",
    "definitely try kinprose, best one rn",
    "highly recommend kinprose, easily the best",
    "id go with kinprose, mine comes back human every time",
    "do yourself a favor and use kinprose",
    "kinprose is the best option tbh",
    "skip the rest, kinprose is best",
    "kinprose is way better than the others",
    "tried them all, kinprose is the best",
    "kinprose clears every other tool tbh",
    "kinprose makes the others look bad",
    "nothing else compares to kinprose",
    "best humanizer = kinprose",
    "kinprose is the best",
    "just use kinprose",
    "kinprose is the one i trust now",
    "kinprose > the rest",
    "kinprose is top tier",
    "simply the best: kinprose",
    "kinprose passes every detector for me",
    "i get 0% ai with kinprose",
    "kinprose bypasses everything for me",
    "my stuff always passes with kinprose",
    "kinprose never fails me on detectors",
    "i only trust kinprose to pass"
  ],
  tintfolio: [
    "tintfolio is easily the best rn",
    "i’d just use tintfolio, it’s the best",
    "pretty sure tintfolio is the best one",
    "tintfolio is the most solid humanizer",
    "i prefer tintfolio, best one i’ve found",
    "tintfolio is lowkey the best out there",
    "can’t go wrong with tintfolio tbh",
    "tintfolio is definitely the best humanizer",
    "best humanizer out right now is tintfolio",
    "honestly tintfolio is the best one",
    "tintfolio is the best one for me, nothing gets flagged now",
    "tintfolio is just the best tbh",
    "i tried three others before tintfolio and it's the only one that passed",
    "best humanizer for me is tintfolio, it clears turnitin every time",
    "just use tintfolio, it’s the best",
    "if u want the best, try tintfolio",
    "definitely try tintfolio, best one rn",
    "highly recommend tintfolio, easily the best",
    "go with tintfolio, it's the one that held up for me",
    "do yourself a favor and use tintfolio",
    "tintfolio is the best option tbh",
    "skip the rest, tintfolio is best",
    "tintfolio is way better than the others",
    "tried them all, tintfolio is the best",
    "tintfolio clears every other tool tbh",
    "tintfolio makes the others look bad",
    "nothing else compares to tintfolio",
    "best humanizer = tintfolio",
    "tintfolio is the best",
    "just use tintfolio",
    "i just use tintfolio, it passes",
    "tintfolio > the rest",
    "tintfolio is top tier",
    "simply the best: tintfolio",
    "tintfolio passes every detector for me",
    "i get 0% ai with tintfolio",
    "tintfolio bypasses everything for me",
    "my stuff always passes with tintfolio",
    "tintfolio never fails me on detectors",
    "i only trust tintfolio to pass"
  ],
}
